import {notFound} from 'next/navigation';import {Header,Footer} from '@/components/SiteChrome';import {connectDB} from '@/lib/db';import {Project} from '@/models';import {fallbackProjects} from '@/lib/content';
const details:any={
'jal-dhara':{fullForm:'जल-धरा',description:'This project is dedicated to conserving water resources and restoring the capacity of dams through desilting operations. The focus is on improving water storage, reducing sedimentation, and ensuring sustainable water supply for agriculture, drinking, and other essential uses.',objectives:['Desilting of dams and reservoirs','Water conservation through recharge and efficient use','Community involvement, training and long-term maintenance'],metrics:[['Water bodies','41'],['Silt excavated','415,888 m³'],['Nearby farms','527'],['Direct beneficiaries','527'],['Indirect beneficiaries','4,505'],['Regained storage','415,888,000 litres']]},
'sies':{description:'Dedicated to strengthening the Indian education system by addressing key challenges and creating opportunities for students across the country.',objectives:['Access to education','Teacher training and development','Curriculum enhancement','Digital learning','Inclusive education']},
'shakti':{description:'Project Shakti is our flagship initiative aimed at empowering women by providing tools, resources and opportunities to lead independent, fulfilling lives.',objectives:['Skill development and vocational training','Entrepreneurship support','Health and well-being','Legal awareness and advocacy','Leadership and community involvement']},
'hard':{description:'Project HARD is dedicated to transforming rural areas into vibrant, self-sustaining communities through sustainable development.',objectives:['Infrastructure development','Agriculture and livelihood support','Education and skill development','Water and sanitation','Community empowerment']},
'tep':{description:'Our Tribal Upliftment project empowers indigenous communities by addressing unique challenges while preserving cultural heritage.',objectives:['Education','Healthcare','Livelihood support','Cultural preservation','Infrastructure development']},
'tefa':{description:'This project promotes sustainable agricultural practices by reviving traditional farming methods that are in harmony with nature.',objectives:['Reviving traditional techniques','Soil health','Water conservation','Biodiversity','Farmer education']},
'heal':{description:'Project HEAL empowers individuals from diverse backgrounds to embrace healthier lifestyles, with focus on women, youth and marginalised communities.',objectives:['Improve physical health','Enhance mental health','Prevent chronic diseases','Empower individuals']},
'sos':{description:'Skill for Success aims to equip participants with essential skills to thrive in their professional and personal lives.',objectives:['Technical skills','Soft skills','Entrepreneurship training','Partnerships','Monitoring and impact assessment']}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;let p:any;try{await connectDB();p=await Project.findOne({slug,published:true}).lean()}catch{}p=p||fallbackProjects.find(x=>x.slug===slug);if(!p)notFound();const d={...(details[slug]||{}),...p};return <><Header/><main><section className="page-hero"><div className="shell"><span className="eyebrow">{d.status||'active'} project</span><h1>{d.name}</h1><p>{d.fullForm}</p></div></section><article className="shell section prose"><h2>About {d.name}</h2><p>{d.description||d.shortDescription}</p>{d.objectives?.length>0&&<><h2>Key objectives</h2><ul>{d.objectives.map((o:string)=><li key={o}>{o}</li>)}</ul></>}{d.metrics?.length>0&&<><h2>Impact</h2><div className="stats-grid">{d.metrics.map((m:any)=><div className="stat" key={m.label||m[0]}><b>{m.value||m[1]}{m.unit?` ${m.unit}`:''}</b><span>{m.label||m[0]}</span></div>)}</div></>}{slug==='jal-dhara'&&<><h2>Site excavation and utilisation</h2><p>The District Administration issued work orders of 9,09,632 Cu M from 61 water bodies. A total of 415,888 cubic metres of silt was excavated from 41 lakes in 12 tehsils, and spread across 527 nearby farms.</p><h2>Environmental impact</h2><p>The work developed an additional storage capacity of 415,888,000 litres. Approximately 831,978,000 litres will also percolate into the ground, improving water tables; the water table of 100+ nearby villages witnessed significant growth.</p></>}</article></main><Footer/></>}
